### ISSUE TITLE
Needs default flowee.conf

### ISSUE THREAD

**Issue by DeftNerd** [floweethehub/flowee-issues#1]
`make install` doesn't seem to install a flowee.conf file anywhere. 

Can we get a default to start with in the repo

It's also a good opportunity to split up the config file into files for each Flowee component (hub, hub-qt, hub-cli, etc)

I envision something like:

* /etc/flowee/flowee.conf - basic configuration that's universal for all components
* /etc/flowee/hub.conf - hub specific configuration settings
* /etc/flowee/hub-cli.conf - hub-cli specific configuration settings
* /etc/flowee/hub-qt.conf - hub-cli specific configuration settings

It would also be nice if the CMake system detected what kind of OS this is running on in order to set up the service configuration files (SystemD, init.d, etc)

**Comment by zander** [comment]
Make install [now](https://github.com/floweethehub/hub/commit/4bf1558f7a1849a4b2a29e473ecb5a135430ceed) installs in etc/flowee/flowee.conf (for release builds).

Additionally I made sure that the method GetConfigFile now no longer assumes one file, but allows multiple. It then takes it from the default location.
So when other components need it, they can use their own config file.
